/*
 * Read tsv generated by Variant Validator and write out in our csv nomenclature format 
 */
process writeVariantValidatorNomenclature {
    publishDir "${params.outdir}", mode: 'symlink'

    input:
    path variant_validator_tsv

    output:
    path "variant_validator_nomenclature.csv", emit: variant_validator_nomenclature

    script:
    """
    python -m rinc.vv.variant_validator_nomenclature \
        --vv_input ${variant_validator_tsv} \
        --nomenclature_output variant_validator_nomenclature.csv
    """
}    
