'''
Created on Jan 16, 2026

Convert transcript effects json to csv 

@author: pleyte
'''
import logging.config
import argparse
from rinc.util.log_config import LogConfig
from rinc.variant_transcript import VariantTranscript
import json
from rinc.util import chromosome_map
from collections import Counter
from rinc.io import variant_helper

class TfxNomenclature(object):
    '''
    classdocs
    '''
    def __init__(self):
        '''
        Constructor
        '''
        self._logger = logging.getLogger(__name__)

    def _get_variant_transcript(self, j:dict):
        """
        Create VariantTrancript using a dict of Tfx values
        """
        v = VariantTranscript(j['chromosome'], j['position'], j['reference'], j['alt'], j['cdnaTranscript'])
        
        v.c_dot = j['cdnaNomenclature']
        v.exon = j['exon']
        
        g_dot_part = j['sequenceVariant']
        refseq_chromosome = chromosome_map.get_refseq(v.chromosome)
        v.g_dot = f"{refseq_chromosome}:{g_dot_part}"
        
        v.gene = j['gene']
        v.genomic_region_type = j['variantType']
        v.p_dot1 = j['proteinNomenclature1']
        v.p_dot3 = j['proteinNomenclature3']
        v.protein_transcript = j['proteinTranscript']
        v.protein_variant_type = j['variantEffect']
        v.additional_fields['splicing'] = j['splicing']
        
        return v
        
    def get_variant_transcripts(self, tfx_json_file: str) -> list[VariantTranscript]:
        """
        """
        count = Counter()
        with open(tfx_json_file, 'r') as f:
            data = json.load(f)
        
        self._logger.info(f"Read {len(data)} tfx from {tfx_json_file}")
        
        variant_transcripts = []
        
        for x in data['transcriptEffects']:
            if not x['cdnaTranscript']:
                count['skip_no_transcript'] += 1
                self._logger.info(f"Skipping variant that doesn't have transcripts: {x['chromosome']}-{x['position']}-{x['reference']}-{x['alt']}-{x['cdnaTranscript']}")
                continue
            elif x['cdnaTranscript'].startswith('CCDS'):
                count['skip_ccds_transcript'] += 1
                #self._logger.debug(f"Skipping CCDS transcript: {x['chromosome']}-{x['position']}-{x['reference']}-{x['alt']}-{x['cdnaTranscript']}")
                continue
                        
            v = self._get_variant_transcript(x)            
            variant_transcripts.append(v)
            count['add_refseq_transcript'] += 1
        
        self._logger.info(f"{count}")
        return variant_transcripts
    
    def write(self, out_filename, variant_transcripts: list[VariantTranscript]):
        """
        """
        variant_helper.write_variant_transcripts(out_filename, variant_transcripts, ['splicing'], 'tfx')
        self._logger.info(f"Wrote {len(variant_transcripts)} variant transcripts to {out_filename}")

def _parse_args():
    parser = argparse.ArgumentParser(description='Use hgvs to determine protein changes for a list of variants')
    parser.add_argument("--version", action="version", version="0.0.1")
    parser.add_argument("--tfx_input", help="File generated by Transcript Effects (json)", required=True)
    parser.add_argument("--out", help="Tfx nomenclature output file (csv)", dest="output", required=True)
    args = parser.parse_args()
    return args    

def main():
    logging.config.dictConfig(LogConfig().stdout_config)

    args = _parse_args()

    tn = TfxNomenclature()
    
    variant_transcripts = tn.get_variant_transcripts(args.tfx_input)
    tn.write(args.output, variant_transcripts)
    
if __name__ == '__main__':
    main()                
        