'''
Extract transcript details from an annovar multianno file and write to a new csv. 

Created on Jan 5, 2026

@author: pleyte
'''
import argparse
import csv
import logging.config
from rinc.util.log_config import LogConfig
from rinc.variant_transcript import VariantTranscript

class AnnovarMultianno(object):
    '''
    classdocs
    '''
    def __init__(self):
        '''
        Constructor
        '''
        self._logger = logging.getLogger(__name__)
    
    def get_variant_transcripts(self, annovar_multianno_file):
        """
        Read the Annovar multianno file generated by ``table_annovar.pl --csvout``.         
        """
        variant_transcripts = []  
        with open(annovar_multianno_file, mode='r', encoding='utf-8') as f:        
            reader = csv.DictReader(f)
            for row in reader:
                for row_transcript in self._get_row_transcripts(row['Gene.refGeneWithVer']):
                    variant_transcript = self._get_parse_transcript(row_transcript, row)
                    variant_transcripts.append(variant_transcript)
        
        return variant_transcripts
    
    def _get_row_transcripts(self, gene_ref_gene_with_ver):
        """
        The annovar multianno file's Gene.refGeneWithVer lists the transcripts at this location. 
        The transcripts may be associated with multiple genes so there may two delimiters used as in: 
        NM_001242366.3,NM_080669.6;NM_015077.4
        
        The semi-colon delimits transcripts associated with different genes. 
        The comma delimts transcripts on the same gene.  
        """
        all_transcripts = []
        
        gene_groups = gene_ref_gene_with_ver.split(';')
        for g in gene_groups:
            all_transcripts.extend(g.split(','))
        
        return all_transcripts
        
        
    def _get_cdna_values(self, transcript: str, gene_detail_field: str):
        """
        The Annovar GeneDetail.refGeneWithVer field which is delimited by ';' and ':'
        """
        if gene_detail_field == '.':
            return None, None
        
        try:
            for gene_detail in gene_detail_field.split(';'):
                if 'exon' in gene_detail:            
                    gene_transcript, exon, c_dot = gene_detail.split(':')
                elif gene_detail.startswith('dist='):
                    # dist=nnn means intergenic. We skipt these in tfx. 
                    return None, None
                else:
                    exon = None
                    gene_transcript, c_dot = gene_detail.split(':')
                    
                if gene_transcript == transcript:
                    return c_dot, exon 
        except ValueError:
            self._logger.warning(f"Could not parse GeneDetail.refGeneWithVer field for {transcript}: {gene_detail_field}")            
            raise
                
        # No information in this field for the current transcript 
        return None, None
        
    def _get_protein_values(self, transcript: str, aa_change_field: str):
        """
        Parse details for a specific transcript from the Annovar AAChange.refGeneWithVer field whch is delimited by ',' and ':'
        """
        if aa_change_field == "." or aa_change_field == "UNKNOWN":
            return None, None, None, None
        
        for aa_detail in aa_change_field.split(","):
            gene, aa_transcript, exon, c_dot, p_dot = aa_detail.split(':')
            if aa_transcript == transcript:
                return gene, exon, c_dot, p_dot
        
        # No information in this field for the current transcript 
        return None, None, None, None
            
        
    def _get_parse_transcript(self, transcript: str, row: dict):
        """
        Extract details for a specific transcript from an annovar row
        """
        variant_transcript = VariantTranscript(row['Chr'], row['Start'], row['Ref'], row['Alt'], transcript)
        variant_transcript.genomic_region_type = row['Func.refGeneWithVer']
        variant_transcript.protein_variant_type = row['ExonicFunc.refGeneWithVer']
                    
        cdna_c_dot, cdna_exon = self._get_cdna_values(transcript, row['GeneDetail.refGeneWithVer'])
        aa_gene, aa_exon, aa_c_dot, aa_p_dot = self._get_protein_values(transcript, row['AAChange.refGeneWithVer'])
        
        # Get the c. from one of two fields
        if cdna_c_dot and aa_c_dot:
            variant_transcript.c_dot = cdna_c_dot
            variant_transcript.notes.append(f"c. from protein field is {aa_c_dot}")
        elif cdna_c_dot:
            variant_transcript.c_dot = cdna_c_dot
        elif aa_c_dot:
            variant_transcript.c_dot = aa_c_dot
            variant_transcript.notes.append("c. is from protein field")
        
        # Exon
        if cdna_exon and aa_exon:
            variant_transcript.exon = cdna_exon
            variant_transcript.notes.append(f"exon from protein field is {aa_exon}")
        elif cdna_exon:
            variant_transcript.exon = cdna_exon
        elif aa_exon:
            variant_transcript.exon = aa_exon
        
        
        # Gene
        variant_transcript.gene = aa_gene
        
        # p.
        variant_transcript.p_dot1 = aa_p_dot

        return variant_transcript

        
    def write(self, out_filename, variant_transcripts: list[VariantTranscript]):
        headers = ['chromosome', 'position', 'reference', 'alt',
                   'cdna_transcript',
                   'annovar.exon', 'annovar.gene', 'annovar.genomic_region_type', 'annovar.protein_variant_type',
                   'annovar.c_dot', 'annovar.p_dot1',
                   'annovar.note']
        
        with open(out_filename, 'w', newline='') as output:
            writer = csv.writer(output)
            writer.writerow(headers)

            for v in variant_transcripts:
                writer.writerow([v.chromosome, v.position, v.reference, v.alt, 
                                 v.cdna_transcript, 
                                 v.exon, v.gene, v.genomic_region_type, v.protein_variant_type,
                                 v.c_dot, v.p_dot1, 
                                 ";".join(v.notes)])
            
        self._logger.info(f"Wrote {len(variant_transcripts)} variant transcripts to {out_filename}")


def _parse_args():
    parser = argparse.ArgumentParser(description='Read Annovar multianno file, extract values and write to new csv')

    parser.add_argument('--annovar_multianno',
                        help='Multianno output from annovar (csv)',
                        required=True)

    parser.add_argument("--out", help="output file (csv)", required=True)

    parser.add_argument("--version", action="version", version="0.0.1")

    return parser.parse_args()


def main():
    logging.config.dictConfig(LogConfig().stdout_config)
    logger = logging.getLogger("rinc.etl.annovar_multianno")

    args = _parse_args()

    am = AnnovarMultianno()
    
    variant_transcripts = am.get_variant_transcripts(args.annovar_multianno)

    am.write(args.out, variant_transcripts)

    logger.info(f"Wrote {len(variant_transcripts)} variant transcripts to {args.out}")


if __name__ == '__main__':
    main()
